name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Deploy movie symfony app
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          cd /home/mmi21g04/public_html/
          git clone git@github.com:SamChrp/Symfony-S5.git
          cd Symfony-s5
          git pull
          composer install
          php bin/console c:c
